import { useState, useEffect, useCallback } from 'react';
import { Product } from '../types';
import { supabase } from '../lib/supabase';
import { toast } from 'sonner';

export function useProductsStore() {
  const [products, setProducts] = useState<Product[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const fetchProducts = useCallback(async () => {
    try {
      setIsLoading(true);
      const { data, error } = await supabase
        .from('products')
        .select('*')
        .order('createdAt', { ascending: false });

      if (error) throw error;
      if (data) {
        const mappedData = data.map((p: any) => {
          if (p.category === 'fabrics' && p.sizes && p.sizes.length > 0) {
            return { ...p, pricingUnit: p.sizes[0], sizes: [] };
          }
          return { ...p, pricingUnit: null };
        });
        setProducts(mappedData as Product[]);
      }
    } catch (error: any) {
      console.error('Error fetching products:', error.message);
      toast.error('Failed to load products');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchProducts();
    
    // Subscribe to real-time changes
    const channel = supabase
      .channel('schema-db-changes')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'products',
        },
        () => {
          fetchProducts();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [fetchProducts]);

  const addProduct = useCallback(async (product: Product) => {
    try {
      // Remove id if it's generated by Date.now() in UI so Supabase can generate a UUID
      // Also ensure date formatting is standard or let Supabase handle it
      const { id, pricingUnit, ...productWithoutId } = product;
      const dbProduct: any = { ...productWithoutId };
      
      if (dbProduct.category === 'fabrics' && pricingUnit) {
        dbProduct.sizes = [pricingUnit];
      }
      
      const { error } = await supabase.from('products').insert([dbProduct]);
      if (error) throw error;
      
      await fetchProducts();
      return true;
    } catch (error: any) {
      console.error('Error adding product:', error.message);
      toast.error(`Failed to add product: ${error.message}`);
      return false;
    }
  }, [fetchProducts]);

  const updateProduct = useCallback(async (product: Product) => {
    try {
      const { id, pricingUnit, ...updateData } = product;
      const dbUpdate: any = { ...updateData };
      
      if (dbUpdate.category === 'fabrics' && pricingUnit) {
        dbUpdate.sizes = [pricingUnit];
      }

      const { error } = await supabase
        .from('products')
        .update(dbUpdate)
        .eq('id', id);
      
      if (error) throw error;
      await fetchProducts();
      return true;
    } catch (error: any) {
      console.error('Error updating product:', error.message);
      toast.error(`Failed to update product: ${error.message}`);
      return false;
    }
  }, [fetchProducts]);

  const removeProduct = useCallback(async (id: string) => {
    try {
      const { error } = await supabase
        .from('products')
        .delete()
        .eq('id', id);
        
      if (error) throw error;
      await fetchProducts();
      return true;
    } catch (error: any) {
      console.error('Error deleting product:', error.message);
      toast.error(`Failed to delete product: ${error.message}`);
      return false;
    }
  }, [fetchProducts]);

  return { products, addProduct, updateProduct, removeProduct, isLoading };
}
